version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  Imperial-Mertic:
    image: ${REGISTRY:-Imperial_Mertic}/Imperial_Mertic.api:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      - "ImperialMerticDb"
    container_name: Imperial_Mertic
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: API/Imperial_Metric.WebApi/Dockerfile 
    environment:
      - ConnectionString=host=worklog_management_db;port=5435;database=ImperialMerticDb;username=postgres;password=postgres;Pooling=true;
    networks:
      - dev

  Imperial_Mertic_db:
    image: postgres:latest
    container_name: ImperialMerticDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ImperialMerticDb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - Imperial_Mertic_Data:/var/lib/postgresql/data/ 
    networks:
      - dev

volumes:
  Imperial_Mertic_Data:
